import { Box, Flex, Text } from "@chakra-ui/react";
import Head from "next/head";
import { Router, useRouter } from "next/router";
import ButtonAtom from "../components/atoms/button/button";
import styles from "../styles/Home.module.css";

export default function Home() {
	const router = useRouter();
	return (
		<Box className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Flex
				justifyContent={"center"}
				alignItems="center"
				height={"80vh"}
				textAlign={"center"}
				flexDirection="column"
				gap={"30px"}
			>
				<Text margin={"0"} fontSize={"60px"}>
					Look Sharp, Feel Confident.
				</Text>
				<Text as={"span"} fontSize="20px">
					Don't you just love being in apparel?
				</Text>
				<ButtonAtom
					onClick={() => {
						router.push("/collections");
					}}
					type={"primary"}
				>
					Shop now
				</ButtonAtom>
			</Flex>
		</Box>
	);
}
